def print_version_info():
    print("Version: 1.0.0\n")
    print("Release Date: 9-10-2026\n")

def print_about_info():
    print(
        "\nAbout Marc/Mentat Data Analyzer:\n")
    print_version_info()
    print("This tool is designed to analyze and process data generated by Marc and Mentat software.\n"
        "It provides various functionalities including report generation, data visualization, and more.\n"
        "For more information, visit the official documentation or github repository.\n")
    print("Github Repository: https://github.com/PszczolkaPL/MarcMentatAnalyzer\n")
    print("Author: Pszczolka\n")
    print("License: MIT License\n")


def print_help_menu():
    print("\n" + "=" * 60)
    print("                AVAILABLE ACTIONS & COMMANDS")
    print("=" * 60)
    print("  load <file.out>      : Load Marc MSC output (.out) file")
    print("  critical             : Show bars expected to fail first & mechanisms")
    print("  max_load <load_kN>   : Calculate maximum point load before failure")
    print("  show_all             : Display table of all parsed members")
    print("  element <id>         : Show detailed inspection for one element")
    print("  set_prop [k=v]       : Set Area, E, Yield Stress, or Shape")
    print("  analyze              : Re-calculate yielding & buckling limits")
    print("  report               : Generate a detailed structural report (for more info type 'report --help')")
    print("  help / --help        : Display this help menu")
    print("  about                : Show information about the tool")
    print("  version              : Show version and release date")
    print("  exit / quit          : Exit application")
    print("=" * 60 + "\n")